{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-module.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.orderService.name }}
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: {{ .Values.orderService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.orderService.name }}
    {{- include "order-module.selectorLabels" . | nindent 4 }}
{{- end }}
