FROM openjdk:8-jre-slim

ARG JAR_FILE
ARG SERVICE_NAME

ENV SERVICE_NAME=${SERVICE_NAME}
ENV JAVA_OPTS="-Xms256m -Xmx512m"

WORKDIR /app

COPY ${JAR_FILE} /app/app.jar
COPY config/ /app/config/

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Dfile.encoding=UTF-8 -jar /app/app.jar --spring.config.location=/app/config/"]
